version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    pull_policy: build
    ports:
      - "127.0.0.1:25010:80"
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: nginx/Dockerfile.php
    pull_policy: build
    networks:
      - internal

networks:
  internal:
    driver: bridge