version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8888:80"
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: nginx/Dockerfile.php
    networks:
      - internal

networks:
  internal:
    driver: bridge